"""Video source catalogue.

Tracks what the viewer can stream from: the bundled sample clip, any uploaded
files, and the local webcam. Uploads are stored under ``data/uploads`` under a
server-generated id, and the uploader's filename is kept only as display text in
a sidecar, never as part of a path.

Everything in this module treats its input as hostile, because ``resolve`` takes
a client-supplied string and hands the result to OpenCV, which will happily open
a local file or a network URL. Two checks matter and both are load-bearing:
the id must match the generated-id shape (``Path.glob`` expands ``..``, so an
unvalidated id escapes the uploads directory), and a URL's scheme must be an
actual streaming protocol (otherwise ``file://`` reads host files and ``http://``
reaches metadata endpoints, rendered back to the caller as annotated frames).
"""

from __future__ import annotations

import logging
import re
import uuid
from pathlib import Path

from .config import Settings
from .exceptions import InvalidFrameError, SourceUnavailableError
from .models import SourceInfo

logger = logging.getLogger(__name__)

ALLOWED_SUFFIXES: frozenset[str] = frozenset(
    {".mp4", ".mov", ".avi", ".mkv", ".mpeg", ".mpg", ".webm"}
)

#: Network stream schemes the server will open. Deliberately excludes `file`
#: (arbitrary host reads) and plain `http` to cloud metadata endpoints is at
#: least narrowed to the streaming protocols this app exists to consume.
ALLOWED_STREAM_SCHEMES: frozenset[str] = frozenset({"rtsp", "rtsps", "rtmp"})

#: Upload ids are generated by `uuid4().hex[:12]`; anything else is not an id.
_UPLOAD_ID_PATTERN = re.compile(r"[0-9a-f]{12}")

SAMPLE_ID = "sample"
WEBCAM_ID = "webcam"


class SourceRegistry:
    """Resolves source ids to concrete OpenCV specs."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._uploads_dir = settings.data_dir / "uploads"
        self._uploads_dir.mkdir(parents=True, exist_ok=True)
        self._sample_path = settings.assets_dir / "sample.mp4"

    @property
    def sample_path(self) -> Path:
        return self._sample_path

    def list(self) -> list[SourceInfo]:
        """Every currently selectable source, newest upload first."""
        items: list[SourceInfo] = []
        if self._sample_path.exists():
            items.append(
                SourceInfo(
                    id=SAMPLE_ID,
                    kind="sample",
                    label="Bundled sample clip",
                    detail=self._sample_path.name,
                )
            )
        items.append(
            SourceInfo(
                id=WEBCAM_ID,
                kind="webcam",
                label="Local webcam",
                detail="device 0",
            )
        )
        uploads = sorted(
            (p for p in self._uploads_dir.iterdir() if _is_video(p)),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        for path in uploads:
            items.append(
                SourceInfo(
                    id=path.stem,
                    kind="file",
                    label=_display_name(path),
                    detail=f"{path.stat().st_size / 1024**2:.1f} MB",
                )
            )
        return items

    def resolve(self, source: str) -> str:
        """Turn a source id or raw spec into something OpenCV can open.

        Raises:
            SourceUnavailableError: the id is unknown or the file has vanished.
        """
        spec = source.strip()
        if not spec:
            spec = SAMPLE_ID
        if spec == SAMPLE_ID:
            if not self._sample_path.exists():
                raise SourceUnavailableError(
                    "no bundled sample clip - run scripts/fetch_sample_video.py"
                )
            return str(self._sample_path)
        if spec == WEBCAM_ID:
            return "0"
        if spec.isdigit():
            return spec
        if "://" in spec:
            return self._resolve_url(spec)

        # Upload ids are server-generated hex. Validating the shape here is what
        # actually stops traversal: `Path.glob` happily expands `..`, so an id of
        # `../../assets/*` would otherwise escape the uploads directory and stream
        # back any video on the host.
        if not _UPLOAD_ID_PATTERN.fullmatch(spec):
            raise SourceUnavailableError(f"unknown source '{source}'")

        matches = [p for p in self._uploads_dir.glob(f"{spec}.*") if _is_video(p)]
        if matches:
            resolved = matches[0].resolve()
            # Belt and braces: even with a validated id, confirm the result is
            # inside the uploads directory before handing it to OpenCV.
            if not resolved.is_relative_to(self._uploads_dir.resolve()):
                raise SourceUnavailableError(f"unknown source '{source}'")
            return str(resolved)
        raise SourceUnavailableError(f"unknown source '{source}'")

    def _resolve_url(self, spec: str) -> str:
        """Allow only real network stream schemes.

        Without this, `file:///C:/...` reads arbitrary host files and
        `http://169.254.169.254/...` reaches cloud metadata endpoints, with the
        response rendered back to the caller as annotated frames.
        """
        scheme = spec.split("://", 1)[0].lower()
        if scheme not in ALLOWED_STREAM_SCHEMES:
            raise SourceUnavailableError(
                f"unsupported source scheme '{scheme}'; allowed: "
                + ", ".join(sorted(ALLOWED_STREAM_SCHEMES))
            )
        return spec

    def save_upload(self, filename: str, stream, max_bytes: int) -> SourceInfo:  # noqa: ANN001
        """Persist an uploaded video and return its catalogue entry.

        The size cap is enforced *while* copying, not after. Writing the whole
        body to disk and then judging it makes `max_bytes` a verdict rather than
        a limit: an oversized upload has already consumed the disk by the time it
        is rejected. Any partial write is removed on every failure path, so a
        client that disconnects mid-upload cannot leave debris in the catalogue.

        Raises:
            InvalidFrameError: unsupported extension, empty body, or over the cap.
        """
        suffix = Path(filename or "").suffix.lower()
        if suffix not in ALLOWED_SUFFIXES:
            raise InvalidFrameError(
                f"unsupported video type '{suffix or filename}'; allowed: "
                + ", ".join(sorted(ALLOWED_SUFFIXES))
            )
        source_id = uuid.uuid4().hex[:12]
        target = self._uploads_dir / f"{source_id}{suffix}"
        chunk_size = 1024 * 1024
        size = 0
        try:
            with target.open("wb") as handle:
                while True:
                    chunk = stream.read(chunk_size)
                    if not chunk:
                        break
                    size += len(chunk)
                    if size > max_bytes:
                        raise InvalidFrameError(f"upload exceeds the {max_bytes} byte limit")
                    handle.write(chunk)
            if size == 0:
                raise InvalidFrameError("upload is empty")
        except Exception:
            target.unlink(missing_ok=True)
            raise

        # Keep the original name for display without letting it touch the path.
        (self._uploads_dir / f"{source_id}.name").write_text(Path(filename).name, encoding="utf-8")
        logger.info("stored upload %s (%s, %d bytes)", source_id, filename, size)
        return SourceInfo(
            id=source_id,
            kind="file",
            label=Path(filename).name,
            detail=f"{size / 1024**2:.1f} MB",
        )


def _is_video(path: Path) -> bool:
    """Filter out the ``.name`` sidecars that live alongside uploads."""
    return path.is_file() and path.suffix.lower() in ALLOWED_SUFFIXES


def _display_name(path: Path) -> str:
    """Prefer the uploader's original filename when we recorded it."""
    sidecar = path.with_suffix(".name")
    if sidecar.exists():
        try:
            return sidecar.read_text(encoding="utf-8").strip() or path.name
        except OSError:
            return path.name
    return path.name
